site_name: Python Project fastapi

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.instant

nav: []
# nav:
#   - Index Page: index.md
#   - Tutorials: tutorials.md
#   - How-To-Guides: how-to-guides.md
#   - Reference: reference.md
#   - Explanation: explanation.md

# to navigate with `/site` content correctly
use_directory_urls: false

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

repo_url: https://github.com/myself659/py-project-fastapi
