---
name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy-documentation:
    runs-on: ubuntu-20.04
    steps:
      # check-out repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      # install poetry
      - name: Install poetry
        run: pipx install poetry==1.8.3
      # set-up python with cache
      - name: Setup Python 3.9.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.9"
          cache: "poetry"
      # install requirements (including dev dependencies)
      - name: Install requirements
        run: poetry install
        # Create the openapi.json from the app
      - name: Create openapi.json
        run: |
          set -o pipefail
          poetry run make create_openapi
      # build & deploy docs
      - name: Build docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -o pipefail
          poetry run make docs-deploy
